language: perl
perl:
  - 5.22
  - 5.24
  - 5.26
  - 5.28
  - 5.30
after_success:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
  - cover -delete
  - perl Build.PL && ./Build build && HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,inc" PERL5LIB="lib" prove t/
  - cover -report coveralls
