badges = ["travis", "coveralls"]
authority = "cpan:GOCCY"

module_maker = "Module::Maker"

[build]
build_class = "builder::MyBuilder"

[no_index]
directory = ['t', 'examples', 'builder', 'experiments']

[FileGatherer]
exclude_match = ['^t/perl/.*', '^example/bigdata.pl', '^experiments/']
